-- 1.Customer overview
-- List all customers with their basic location information.
select 
	company_name,
	country,
	city
from 
	customers
;

-- 2.Products on stock (high-priced, active products)
-- Identify products that are not discontinued and have been sold
-- with a unit price greater than 30.
-- The count indicates how often such products appear in order details.
select
	prod.product_name,
	count(prod.product_name) as sales_count
from 
	products prod
join 
	order_details od on prod.product_id = od.product_id 
where 
	od.unit_price > 30 and 
	prod.discontinued = 0
group by 
	prod.product_name
;

-- 3.Orders per customer
-- Count how many orders each customer has placed.
select
	cus.contact_name,
	count(o.order_id) as order_count
from 
	orders o
join 
	customers cus on o.customer_id = cus.customer_id 
group by 
	cus.contact_name
;

-- 4.Total sales per order
-- Calculate the total revenue for each individual order.
-- Aggregates all order details belonging to the same order.
select 
	order_id,
	sum(unit_price * quantity * (1 - discount)) as total_sales 
from 
	order_details
group by 
	order_id
;

-- 5.Sales per customer
-- Calculate total revenue generated by each customer across all orders.
select
	c.contact_name,
	sum(od.unit_price * od.quantity * (1 - od.discount)) as total_sales 
from 
	orders o
join 
	order_details od on o.order_id = od.order_id
join 
	customers c on c.customer_id = o.customer_id 
group by 
	c.contact_name
;

-- 6.Total sales per month
-- Calculate total revenue per calendar month across all years.
select
	extract(year from o.order_date) as order_year,
	extract(month from o.order_date) as order_month,
	sum(od.unit_price * od.quantity * (1 - od.discount)) as total_sales_monthly
from 
	orders o
join 
	order_details od on o.order_id = od.order_id
group by 
	order_year, 
	order_month
order by 
	order_year, 
	order_month
;

-- 6.Total sales per year
-- Calculate total revenue per year.
select
	extract(year from o.order_date) as order_year,
	sum(od.unit_price * od.quantity * (1 - od.discount)) as total_sales_yearly
from 
	orders o
join 
	order_details od on o.order_id = od.order_id
group by 
	order_year
order by 
	order_year
;

-- 7.Top product per category
-- Identify the top-selling product (by total revenue)
-- within each product category.
select distinct on (category_name)
	cat.category_name,
	prod.product_name,
	sum(od.unit_price * od.quantity * (1 - od.discount)) as total_sales
from 
	order_details od
join 
	products prod on od.product_id = prod.product_id
join 
	categories cat on prod.category_id = cat.category_id
group by 
	cat.category_name, 
	prod.product_name
order by 
	cat.category_name, 
	total_sales desc, 
	product_name
;

-- 8.Inactive customers
-- Identify customers who had a gap of at least 365 days
-- between two consecutive orders.
select
	sub.contact_name,
	sub.date_diff as inactive_days
from (
	select
		o.order_id,
		cus.contact_name,
		o.order_date,
		o.order_date - lag(o.order_date) over(partition by cus.contact_name order by o.order_date) as date_diff
	from 
		orders o 
	join 
		customers cus on o.customer_id = cus.customer_id
) sub
where 
	sub.date_diff >= 365
order by 
	inactive_days desc
;

-- 9.Customer ranking
-- Rank customers within each country by their total revenue.
-- Customers with the same revenue share the same rank.
select
	cus.country,
	cus.contact_name,
	rank() over(partition by cus.country order by sum(od.unit_price * od.quantity * (1 - od.discount)) desc) as customer_rank
from 
	orders o
join 
	customers cus on o.customer_id = cus.customer_id
join 
	order_details od on o.order_id = od.order_id
group by 
	cus.country, 
	cus.contact_name
;

-- 10.Employee performance
-- Evaluate employee performance based on total revenue,
-- number of handled orders, and average sales per order detail.
-- Includes a global ranking by total revenue.
select
	rank() over (
		order by sum(od.unit_price * od.quantity * (1 - od.discount)) desc
	) as sales_rank,
	emp.employee_id, 
	emp.first_name,
	emp.last_name,
	count(o.order_id) as orders,
	sum(od.unit_price * od.quantity * (1 - od.discount)) as total_sales,
	avg(od.unit_price * od.quantity * (1 - od.discount)) as avg_sales
from 
	orders o
join 
	order_details od on o.order_id = od.order_id
join 
	employees emp on o.employee_id = emp.employee_id
group by 
	emp.employee_id
order by 
	total_sales desc
;

-- 11.Customers with only on-time deliveries
-- Identify customers for whom all orders were delivered
-- on or before the required date.
select
	cus.contact_name,
	min(o.required_date - o.order_date) as expected_delivery_time,
	min(o.shipped_date - o.order_date) as actual_delivery_time
from 
	orders o
join 
	customers cus on o.customer_id = cus.customer_id
group by 
	cus.contact_name 
having 
	min(o.required_date - o.order_date) >= min(o.shipped_date - o.order_date)
;

-- 12.Products with strictly increasing yearly sales
-- Identify products whose total yearly sales
-- strictly increase year over year without any decline.
with t_sales_diff as (
	select
		prod.product_name,
		(
			sum(od.unit_price * od.quantity * (1 - od.discount)) >
			lag(sum(od.unit_price * od.quantity * (1 - od.discount)))
			over(partition by prod.product_name order by extract(year from o.order_date))
		)::int as sales_diff
	from 
		orders o
	join 
		order_details od on o.order_id = od.order_id
	join 
		products prod on od.product_id = prod.product_id
	group by 
		prod.product_name, 
		extract(year from o.order_date)
)
select
	product_name
from 
	t_sales_diff
group by 
	product_name
having 
	min(sales_diff) <> 0
order by 
	product_name
;

-- 13.Countries where a product performs above its average
-- For each product, identify countries where its total sales
-- are above the product's average sales across all countries.
with t_total_sales_per_country_product as (
	select 
		prod.product_name,
		cus.country,
		sum(od.unit_price * od.quantity * (1 - od.discount)) as total_sales_per_country
	from 
		orders o
	join 
		order_details od on o.order_id = od.order_id
	join 
		products prod on od.product_id = prod.product_id
	join 
		customers cus on o.customer_id = cus.customer_id
	group by 
		prod.product_name, 
		cus.country
),
t_avg_sales_per_product as (
	select 
		product_name,
		avg(total_sales_per_country) as avg_sales_per_product
	from 
		t_total_sales_per_country_product
	group by 
		product_name
)
select 
	asp.product_name,
	tscp.country,
	tscp.total_sales_per_country,
	asp.avg_sales_per_product
from 
	t_avg_sales_per_product asp
join 
	t_total_sales_per_country_product tscp on asp.product_name = tscp.product_name
where 
	tscp.total_sales_per_country >= asp.avg_sales_per_product
order by 
	asp.product_name, 
	tscp.country
;

-- 14.Discount usage and perfect delivery customers
-- Identify customers who:
-- 1) Have received at least one discount
-- 2) Had all their orders delivered on time
with t_customer_flag as (
	select 
		cus.contact_name,
		bool_or(od.discount <> 0) over(partition by cus.contact_name, o.order_id) as has_discount,
		o.shipped_date <= o.required_date as delivered_on_time
	from 
		orders o
	join 
		order_details od on o.order_id = od.order_id 
	join 
		customers cus on o.customer_id = cus.customer_id
)
select 
	contact_name
from 
	t_customer_flag
group by 
	contact_name
having 
	bool_or(has_discount) and 
	bool_and(delivered_on_time)
order by 
contact_name
;

-- 15.Products with continuous yearly growth
-- Identify products that:
-- 1) Have sales in consecutive years (no gaps)
-- 2) Show strictly increasing yearly total sales
with sales_products_per_year as (
	select
	    prod.product_name,
	    extract(year from o.order_date) as order_year,
	    sum(od.unit_price * od.quantity * (1 - od.discount)) as total_sales
	from 
		orders o
	join 
		order_details od on o.order_id = od.order_id
	join 
		products prod on od.product_id = prod.product_id
	group by 
		prod.product_name, 
		order_year
),
t_sales_date_flag as (
	select 
		*,
		coalesce(order_year - lag(order_year) over(partition by product_name order by order_year), 0) as year_diff,
		(total_sales > lag(total_sales) over(partition by product_name order by order_year))::int as sales_increase
	from sales_products_per_year
),
t_filter_products as (
	select 
		product_name
	from 
		t_sales_date_flag
	group by 
		product_name
	having 
		bool_and(
			(year_diff = 0) or (
			 year_diff = 1 and 
			 sales_increase = 1
			)
	)
)
select 
	spy.*
from 
	t_filter_products fp
join 
	sales_products_per_year spy on fp.product_name = spy.product_name
;

-- 16.Products with low yearly sales volatility
-- Identify products whose yearly sales variability
-- remains within 10% of their minimum observed variation.
-- Variability is measured using the coefficient of variation.
with t_stats_sales as (
	select
	    prod.product_name,
	    extract(year from o.order_date) as order_year,
	    sum(od.unit_price * od.quantity * (1 - od.discount)) as total_sales,
	    avg(od.unit_price * od.quantity * (1 - od.discount)) as avg_sales,
	    stddev(od.unit_price * od.quantity * (1 - od.discount)) as std_sales
	from 
		orders o
	join 
		order_details od on o.order_id = od.order_id
	join 
		products prod on od.product_id = prod.product_id
	group by 
		prod.product_name, order_year
),
t_stats_sales_var_coeff as (
	select
		*,
		std_sales / avg_sales as var_coeff,
		min(std_sales / avg_sales) over(partition by product_name) * 1.1 as max_allowed_var
	from 
		t_stats_sales
),
t_filter_products as (
	select 
		product_name
	from 
		t_stats_sales_var_coeff
	group by 
		product_name
	having 
		bool_and(var_coeff <= max_allowed_var)
)
select 
	sts.*,
	stsvc.var_coeff
from 
	t_filter_products fp
join 
	t_stats_sales sts on sts.product_name = fp.product_name
join 
	t_stats_sales_var_coeff stsvc on stsvc.product_name = sts.product_name and 
	stsvc.order_year = sts.order_year
;

-- Executive KPI view
-- Provide a yearly executive-level KPI overview including:
-- - total sales
-- - number of distinct customers
-- - top-selling product
-- - top-selling category
drop view if exists exec_kpi_view;

create or replace view exec_kpi_view as
with t_order_base as (
    -- Base fact table at order-line level
    select
        extract(year from o.order_date) as order_year,
        o.order_id, 
        od.product_id,
        od.unit_price * od.quantity * (1 - od.discount) as total_sales,
        o.customer_id
    from 
    	orders o
    join 
    	order_details od on o.order_id = od.order_id
), 
t_total_sales_count_customers as (
    -- Aggregate total sales and distinct customers per year
    select
        ob.order_year,
        sum(ob.total_sales) as total_sales,
        count(distinct ob.customer_id) as count_customers
    from 
    	t_order_base ob
    group by 
    	ob.order_year
),
t_top_product as (
    -- Identify the top-selling product per year
    select distinct on (ob.order_year)
        ob.order_year,
        p.product_name as top_product,
        sum(ob.total_sales) as total_sales_product
    from 
    	t_order_base ob
    join products p on ob.product_id = p.product_id
    group by
        ob.order_year,
        p.product_name
    order by
        ob.order_year,
        total_sales_product desc,
        p.product_name
),
t_top_category as (
    -- Identify the top-selling category per year
    select distinct on (ob.order_year)
        ob.order_year,
        c.category_name as top_category,
        sum(ob.total_sales) as total_sales_category
    from 
    	t_order_base ob
    join 
    	products p on p.product_id = ob.product_id
    join 
    	categories c on p.category_id = c.category_id
    group by
        ob.order_year,
        c.category_name
    order by
        ob.order_year,
        total_sales_category desc,
        c.category_name
)
select 
    tscc.order_year,
    tscc.total_sales,
    tscc.count_customers,
    tp.top_product,
    tc.top_category
from 
	t_total_sales_count_customers tscc
join 
	t_top_product tp on tscc.order_year = tp.order_year
join 
	t_top_category tc on tscc.order_year = tc.order_year
order by
    tscc.order_year
;
	
	
	
	
	
	